(defproblem problem_d1_r0_l8_p8_c14_g12 emergency
(
  (at drone1 depot)
  (libre drone1 brazo1)
  (at crate1 depot)
  (tipo crate1 food)
  (at crate2 depot)
  (tipo crate2 food)
  (at crate3 depot)
  (tipo crate3 food)
  (at crate4 depot)
  (tipo crate4 food)
  (at crate5 depot)
  (tipo crate5 food)
  (at crate6 depot)
  (tipo crate6 medicine)
  (at crate7 depot)
  (tipo crate7 medicine)
  (at crate8 depot)
  (tipo crate8 medicine)
  (at crate9 depot)
  (tipo crate9 medicine)
  (at crate10 depot)
  (tipo crate10 medicine)
  (at crate11 depot)
  (tipo crate11 medicine)
  (at crate12 depot)
  (tipo crate12 medicine)
  (at crate13 depot)
  (tipo crate13 medicine)
  (at crate14 depot)
  (tipo crate14 medicine)
  (at person1 loc7)
  (necesita person1 food)
  (necesita person1 medicine)
  (at person2 loc5)
  (necesita person2 food)
  (at person3 loc2)
  (necesita person3 medicine)
  (at person4 loc4)
  (necesita person4 medicine)
  (at person5 loc6)
  (necesita person5 food)
  (necesita person5 medicine)
  (at person6 loc4)
  (necesita person6 medicine)
  (at person7 loc8)
  (necesita person7 food)
  (necesita person7 medicine)
  (at person8 loc7)
  (necesita person8 food)
  (necesita person8 medicine)
)
(
  (enviar-todo)
)
)
