(defproblem problem emergency
(
  (at drone1 depot)
  (libre drone1 brazo1)
  (at crate1 depot)
  (tipo crate1 food)
  (at crate2 depot)
  (tipo crate2 food)
  (at crate3 depot)
  (tipo crate3 medicine)
  (at crate4 depot)
  (tipo crate4 medicine)
  (at person1 loc2)
  (necesita person1 food)
  (at person2 loc3)
  (necesita person2 food)
  (at person3 loc3)
  (necesita person3 medicine)
  (at person4 loc4)
  (necesita person4 medicine)
)
(
  (enviar-todo)
)
)
