(defproblem problem emergency
(
  (at drone1 depot)
  (libre drone1 brazo1)
  (libre drone1 brazo2)
  (at crate1 depot)
  (tipo crate1 food)
  (at crate2 depot)
  (tipo crate2 food)
  (at crate3 depot)
  (tipo crate3 food)
  (at crate4 depot)
  (tipo crate4 food)
  (at crate5 depot)
  (tipo crate5 medicine)
  (at crate6 depot)
  (tipo crate6 medicine)
  (at crate7 depot)
  (tipo crate7 medicine)
  (at crate8 depot)
  (tipo crate8 medicine)
  (at crate9 depot)
  (tipo crate9 medicine)
  (at crate10 depot)
  (tipo crate10 medicine)
  (at person1 loc8)
  (necesita person1 medicine)
  (at person2 loc10)
  (necesita person2 food)
  (at person3 loc3)
  (necesita person3 medicine)
  (at person4 loc5)
  (necesita person4 medicine)
  (at person5 loc10)
  (necesita person5 food)
  (at person6 loc1)
  (at person7 loc4)
  (necesita person7 food)
  (necesita person7 medicine)
  (at person8 loc1)
  (at person9 loc10)
  (necesita person9 medicine)
  (at person10 loc5)
  (necesita person10 food)
  (necesita person10 medicine)
)
(
  (enviar-todo)
)
)
