(defproblem problem_d1_r0_l3_p3_c6_g4 emergency
(
  (at drone1 depot)
  (libre drone1 brazo1)
  (at crate1 depot)
  (tipo crate1 food)
  (at crate2 depot)
  (tipo crate2 medicine)
  (at crate3 depot)
  (tipo crate3 medicine)
  (at crate4 depot)
  (tipo crate4 medicine)
  (at crate5 depot)
  (tipo crate5 medicine)
  (at crate6 depot)
  (tipo crate6 medicine)
  (at person1 loc1)
  (necesita person1 medicine)
  (at person2 loc1)
  (necesita person2 medicine)
  (at person3 loc2)
  (necesita person3 food)
  (necesita person3 medicine)
)
(
  (enviar-todo)
)
)
