(defproblem problem emergency
(
  (at drone1 depot)
  (libre drone1 brazo1)
  (libre drone1 brazo2)
  (at crate1 depot)
  (tipo crate1 food)
  (at crate2 depot)
  (tipo crate2 medicine)
  (at crate3 depot)
  (tipo crate3 medicine)
  (at crate4 depot)
  (tipo crate4 medicine)
  (at crate5 depot)
  (tipo crate5 medicine)
  (at person1 loc5)
  (necesita person1 medicine)
  (at person2 loc2)
  (necesita person2 medicine)
  (at person3 loc2)
  (necesita person3 food)
  (necesita person3 medicine)
  (at person4 loc1)
  (necesita person4 medicine)
  (at person5 loc5)
)
(
  (enviar-todo)
)
)
