(defproblem problem_d1_r0_l5_p5_c10_g8 emergency
(
  (at drone1 depot)
  (libre drone1 brazo1)
  (at crate1 depot)
  (tipo crate1 food)
  (at crate2 depot)
  (tipo crate2 food)
  (at crate3 depot)
  (tipo crate3 food)
  (at crate4 depot)
  (tipo crate4 food)
  (at crate5 depot)
  (tipo crate5 food)
  (at crate6 depot)
  (tipo crate6 medicine)
  (at crate7 depot)
  (tipo crate7 medicine)
  (at crate8 depot)
  (tipo crate8 medicine)
  (at crate9 depot)
  (tipo crate9 medicine)
  (at crate10 depot)
  (tipo crate10 medicine)
  (at person1 loc2)
  (necesita person1 food)
  (at person2 loc3)
  (necesita person2 food)
  (necesita person2 medicine)
  (at person3 loc1)
  (necesita person3 food)
  (at person4 loc1)
  (necesita person4 food)
  (necesita person4 medicine)
  (at person5 loc4)
  (necesita person5 food)
  (necesita person5 medicine)
)
(
  (enviar-todo)
)
)
